ALTER TABLE "user"
DROP COLUMN company;

ALTER TABLE "user"
DROP COLUMN subdomain;

CREATE TABLE tenant (
    id SERIAL PRIMARY KEY,
    company CHARACTER VARYING(255) NOT NULL UNIQUE ,
    subdomain CHARACTER VARYING(64) NOT NULL UNIQUE,
    status INTEGER NOT NULL
);

ALTER TABLE "user"
ADD COLUMN tenant_id INTEGER NOT NULL;

ALTER TABLE "user"
ADD FOREIGN KEY (tenant_id)
REFERENCES tenant(id)
ON DELETE CASCADE ;
